# main text of home
name: Ilias Van Peer
bio: Coffee. Code. Whiskey.

# twitter summary info
# description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.png

url: https://ilias.xyz
enforce_ssl: ilias.xyz
# your url: http://USERNAME.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
analytics-google: 'UA-27384029-1'
disqus: ilias-xyz

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: zwilias
# youtube: myyoutube
# spotify: myspotify
github: zwilias
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
email: mail@ilias.xyz
soundcloud: zwilias
distiller: zwop

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# For identifying the author at the bottom of posts
authors:
    ilias:
        name: Ilias Van Peer
        bio: Coffee. Code. Whiskey.
        external-image: false
        picture: assets/images/profile.png
        #twitter: johndoe

# Sections
projects: true
about: true
blog: true

# options
read-time: true
show-tags: true
related: true
blog-nav-links: false
show-author: true
animation: true

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-timeago

jekyll-mentions:
    base_url: https://github.com
